### ISSUE TITLE
DeepONet should support arbitrary trunk/branch networks

### ISSUE THREAD

**Issue by samuelburbulla** [aai-institute/continuiti#71]
Currently, we implement the DeepONet with fully connected networks for branch and trunk. Depending on the problem, one would like to replace these networks by more appropriate ones (e.g. CNNs as branch network).

Generalize DeepONet to take branch/trunk network in constructor. Per default, it should use DeepResidualNetwork.

**Comment by JinglaiZheng** [comment]
Thank you so much for your library. As a PhD student who regularly uses PINN, I intend to use continuiti to start my deeponet journey. My goal is very clear, to achieve PDE solution when the input of the branch network is in the form of images, such as spatially distributed material parameters, which I think can provide information in the form of images. Knowing that your library can implement CNN as a branch network, I started researching continuiti and asked if I could provide an example of CNN as a branch network or any other insights, thank you very much!

**Comment by JinglaiZheng** [comment]
Thank you so much for your library.  As a PhD student who regularly uses PINN, I intend to use continuiti to start my deeponet journey.  My goal is very clear, to achieve PDE solution when the input of the branch network is in the form of images, such as spatially distributed material parameters, which I think can provide information in the form of images.  Knowing that your library can implement CNN as a branch network, I started researching continuiti. Could you provide an example of CNN as a branch network or any other insights, thank you very much!

**Comment by samuelburbulla** [comment]
Hi Jinglai, thank you for reaching out!
Our current implementation of DeepONet does not allow custom branch/trunk networks, but it can be extended to include this functionality - that's why this issue exists. Given your interest, I will prioritize this issue and we will open a PR in coming days with an example.
We welcome any feedback you have once you start using it.

**Comment by samuelburbulla** [comment]
Hi @JinglaiZheng,

I implemented the possibility to use custom branch/trunk network in DeepONet in #149.

See [this test](https://github.com/aai-institute/continuiti/pull/149/files#diff-9b4006beab1345052eb83f89bcd6a8b7e252bdfd4530bb9fd6479f6b3d54ac2e) for an example on how to use it with a CNN as branch network.

Will this suit your needs?

Best,
Samuel
